queues:
  game_commands:
    consumers:
      - App\Consumer\GameOperationConsumer

queue_coroutines_amount: 2

firewalls:
  game_operation_firewall:
    class: App\Firewall\GameOperationFirewall
    consumers:
      - App\Consumer\GameOperationConsumer