services:
    php:
        build:
            context: './../'
            dockerfile: 'docker/php/Dockerfile'
        volumes:
            - "../:/var/www/html"   
        ports:
            - ${PHP_HOST_PORT}:8000


