services:
    php_swoole_composer:
        build:
            context: './../'
            dockerfile: 'docker/php_swoole_composer/Dockerfile'
        volumes:
            - "../:/var/www/html"   
        ports:
            - ${PHP_HOST_PORT}:8000


