name: Github CI Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_testing:
    runs-on: ubuntu-latest

    container:
      image: phpswoole/swoole:latest
      env:
        NODE_ENV: development
      volumes:
        - my_docker_volume:/volume_mount

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies via Composer
        run: composer install

      - name: Run App.php
        run: php src/app.php

      - name: Run Unit-tests
        run: php vendor/bin/phpunit tests    